version: 2
updates:
  # ルートのpackage.jsonの更新設定
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"

  # apps配下のパッケージの更新設定
  - package-ecosystem: "npm"
    directory: "/apps/*"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"

  # packages配下のパッケージの更新設定
  - package-ecosystem: "npm"
    directory: "/packages/*"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"

  # GitHub Actionsの更新設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
